name: Dependency check
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dep_check:
    name: dep_check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          # Install a specific version of uv.
          version: "0.6.9"

      - name: Set up Python
        run: uv python install

      - name: Check import
        run: uv run python -c "from anchorpy import Program"
